# Serving
title: LHBZR
description: Front-End Developer
baseurl: ""
url: "http://lhbzr.github.io"

# User
email: Luis@dotcore.com.br
github: lhbzr
behance: lhbzr
linkedin: lhbzr
tumblr: dotcore

# Handling Reading
encoding: utf-8
include: [".htacess"]
exclude: ["node_modules", "src", "tasks", "Gruntfile.js", "package.json"]

# Conversion
markdown: kramdown
highlighter: rouge
